# Car datasets

In [1]:
import numpy as np;
import pandas as pd;
import utils_ as uti;

In [2]:
cars_df = pd.read_csv("../Assignments/datasets/auto-mpg.data", names=["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name"]);
cars_df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet-chevelle-malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick-skylark-320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth-satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc-rebel-sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford-torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford-mustang-gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw-pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge-rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford-ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy-s-10

In [3]:
#Place mpg as last feature
cars_df = cars_df.reindex(columns=["cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name", "mpg"])
cars_df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name,mpg
0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet-chevelle-malibu,18.0
1,8,350.0,165.0,3693.0,11.5,70,1,buick-skylark-320,15.0
2,8,318.0,150.0,3436.0,11.0,70,1,plymouth-satellite,18.0
3,8,304.0,150.0,3433.0,12.0,70,1,amc-rebel-sst,16.0
4,8,302.0,140.0,3449.0,10.5,70,1,ford-torino,17.0
...,...,...,...,...,...,...,...,...,...
393,4,140.0,86.00,2790.0,15.6,82,1,ford-mustang-gl,27.0
394,4,97.0,52.00,2130.0,24.6,82,2,vw-pickup,44.0
395,4,135.0,84.00,2295.0,11.6,82,1,dodge-rampage,32.0
396,4,120.0,79.00,2625.0,18.6,82,1,ford-ranger,28.0
397,4,119.0,82.00,2720.0,19.4,82,1,chevy-s-10,31.0

In [4]:
#Shrink the values of "weight" using log function
cars_df["weight"] = cars_df["weight"].apply(lambda x: np.log(x));

In [5]:
cars_df

,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name,mpg
0,8,307.0,130.0,8.161660,12.0,70,1,chevrolet-chevelle-malibu,18.0
1,8,350.0,165.0,8.214194,11.5,70,1,buick-skylark-320,15.0
2,8,318.0,150.0,8.142063,11.0,70,1,plymouth-satellite,18.0
3,8,304.0,150.0,8.141190,12.0,70,1,amc-rebel-sst,16.0
4,8,302.0,140.0,8.145840,10.5,70,1,ford-torino,17.0
...,...,...,...,...,...,...,...,...,...
393,4,140.0,86.00,7.933797,15.6,82,1,ford-mustang-gl,27.0
394,4,97.0,52.00,7.663877,24.6,82,2,vw-pickup,44.0
395,4,135.0,84.00,7.738488,11.6,82,1,dodge-rampage,32.0
396,4,120.0,79.00,7.872836,18.6,82,1,ford-ranger,28.0
397,4,119.0,82.00,7.908387,19.4,82,1,chevy-s-10,31.0

In [6]:
analysis = cars_df.drop(["car_name", "origin"], axis="columns");

In [7]:
analysis

,cylinders,displacement,horsepower,weight,acceleration,model_year,mpg
0,8,307.0,130.0,8.161660,12.0,70,18.0
1,8,350.0,165.0,8.214194,11.5,70,15.0
2,8,318.0,150.0,8.142063,11.0,70,18.0
3,8,304.0,150.0,8.141190,12.0,70,16.0
4,8,302.0,140.0,8.145840,10.5,70,17.0
...,...,...,...,...,...,...,...
393,4,140.0,86.00,7.933797,15.6,82,27.0
394,4,97.0,52.00,7.663877,24.6,82,44.0
395,4,135.0,84.00,7.738488,11.6,82,32.0
396,4,120.0,79.00,7.872836,18.6,82,28.0
397,4,119.0,82.00,7.908387,19.4,82,31.0

In [8]:
analysis_2 = analysis.apply(lambda row: uti.convertToNAN(row, analysis.columns, ["?"], np.NaN), axis="columns");

In [9]:
a = analysis_2.iloc[:, 2][analysis.iloc[:, 2] == "?"]
analysis_2.iloc[a.axes[0], :]

,cylinders,displacement,horsepower,weight,acceleration,model_year,mpg
32,4,98.0,NaN,7.623642,19.0,71,25.0
126,6,200.0,NaN,7.963808,17.0,74,21.0
330,4,85.0,NaN,7.514800,17.3,80,40.9
336,4,140.0,NaN,7.974189,14.3,80,23.6
354,4,100.0,NaN,7.749322,15.8,81,34.5
374,4,151.0,NaN,8.017967,20.5,82,23.0

In [10]:
analysis_2.head(-36)

,cylinders,displacement,horsepower,weight,acceleration,model_year,mpg
0,8,307.0,130.0,8.161660,12.0,70,18.0
1,8,350.0,165.0,8.214194,11.5,70,15.0
2,8,318.0,150.0,8.142063,11.0,70,18.0
3,8,304.0,150.0,8.141190,12.0,70,16.0
4,8,302.0,140.0,8.145840,10.5,70,17.0
...,...,...,...,...,...,...,...
357,4,119.0,100.0,7.869019,14.8,81,32.9
358,4,120.0,74.00,7.876638,18.3,81,31.6
359,4,141.0,80.00,8.080237,20.4,81,28.1
360,6,145.0,76.00,8.058327,19.6,81,30.7
361,6,168.0,116.0,7.972466,12.6,81,25.4

In [11]:
#Since we have missing values for horse power, build a model for it first using the other values then /
#Predict and the missing value
#Lateron use the final table and build model for mpg

In [12]:
analysis_2_withoutNAN = analysis_2.drop(a.axes[0], axis="index");
analysis_2_NAN = analysis_2.iloc[a.axes[0], :];
analysis_2_withoutNAN = analysis_2_withoutNAN.reindex(columns=["cylinders", "displacement", "weight", "mpg", "model_year", "acceleration", "horsepower"]);
analysis_2_withoutNAN

,cylinders,displacement,weight,mpg,model_year,acceleration,horsepower
0,8,307.0,8.161660,18.0,70,12.0,130.0
1,8,350.0,8.214194,15.0,70,11.5,165.0
2,8,318.0,8.142063,18.0,70,11.0,150.0
3,8,304.0,8.141190,16.0,70,12.0,150.0
4,8,302.0,8.145840,17.0,70,10.5,140.0
...,...,...,...,...,...,...,...
393,4,140.0,7.933797,27.0,82,15.6,86.00
394,4,97.0,7.663877,44.0,82,24.6,52.00
395,4,135.0,7.738488,32.0,82,11.6,84.00
396,4,120.0,7.872836,28.0,82,18.6,79.00
397,4,119.0,7.908387,31.0,82,19.4,82.00

# Models: Regression Problem - predict horsepower for missing values

In [297]:
from sklearn.linear_model import ElasticNet;
from sklearn.linear_model import LinearRegression;
from sklearn.svm import LinearSVR;
from sklearn.ensemble import RandomForestRegressor;
from sklearn.svm import SVR;
from sklearn.model_selection import LeaveOneOut;
from sklearn.model_selection import cross_val_score;

In [329]:
lin_reg = LinearRegression();
lin_reg_elast = ElasticNet(max_iter=90000, l1_ratio=1, positive=False, tol=0.000001, selection='random');#para
LSVR = LinearSVR(max_iter=90000);#non-para
SVr = SVR(kernel="linear", C=1.3);#non-para
RFR = RandomForestRegressor(n_estimators=40);#non-para

In [330]:
kf = LeaveOneOut();#KFold(n_splits=390, shuffle=True, random_state=32);

In [331]:
x = analysis_2_withoutNAN.drop(["mpg", "displacement", "weight", "horsepower"], axis="columns");
y = analysis_2_withoutNAN.loc[:, "horsepower"];

# Model Validation Techniques:
### Cross Validation:
####     -KFold: (Low Bias at KFold = 10)
####     -LOOCV (Leave-One-Out-Cross-Validation): Most Accurate, omputationally expensive

In [332]:
cv = LeaveOneOut();#Because my data set < 500 rows

In [346]:
lin_reg_ = np.absolute(np.mean(cross_val_score(lin_reg, x, y, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)));
lin_reg_elast_ = np.absolute(np.mean(cross_val_score(lin_reg_elast, x, y, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)));
LSVR_ = np.absolute(np.mean(cross_val_score(LSVR, x, y, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)));
SVr_ = np.absolute(np.mean(cross_val_score(SVr, x, y, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)));
RFR_ = np.absolute(np.mean(cross_val_score(RFR, x, y, scoring="neg_mean_absolute_error", cv=cv, n_jobs=-1)));

KeyboardInterrupt:

In [335]:
print(lin_reg_, lin_reg_elast_, LSVR_, SVr_, RFR_);#Sure that the smallest here is good

-12.795568965542632 -12.73563754505269 -13.801497102128266 -12.495728111224247 -12.78571817850517

In [340]:
results = np.array([lin_reg_, lin_reg_elast_, LSVR_, SVr_, RFR_]);

In [345]:
results

array([-12.79556897, -12.73563755, -13.8014971 , -12.49572811,
       -12.78571818])